name: project_end
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.9.2 <4.0.0"  # Especificamos un rango de versiones para el SDK

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3  
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  fl_chart: ^0.65.0
  intl: ^0.20.2
  signature: ^6.3.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/VSinFondo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/FondoLogin.jpg
    - assets/VManage.png
    - assets/GVMLogo.png
    - assets/VSinFondo.png
